"""
analyzer.py
-----------
Core ML brain of the project.

Reads medication scan timestamps (from simulated_scans.json OR ThingSpeak)
and detects whether the patient's dosing pattern is drifting — predicting
a future missed dose BEFORE it happens.

Two-layer detection:
  Layer 1 — Z-score rule engine  : works from day 1, very fast
  Layer 2 — Isolation Forest ML  : kicks in after 7+ days of data

Run standalone to test:
    python analyzer.py

Returns a result dict that firebase_writer.py sends to Firestore.
"""

import json
import statistics
from datetime import datetime, timedelta


# ── Try importing ML library (optional — falls back to Z-score if missing) ────
try:
    from sklearn.ensemble import IsolationForest
    import numpy as np
    ML_AVAILABLE = True
except ImportError:
    ML_AVAILABLE = False
    print("[WARN] scikit-learn not installed. Using Z-score only.")
    print("       Install with: pip install scikit-learn numpy\n")
# ─────────────────────────────────────────────────────────────────────────────


def load_simulated_data(filepath="simulated_scans.json"):
    """Load scans generated by simulate_data.py"""
    with open(filepath, "r") as f:
        return json.load(f)


def extract_daily_intakes(scans):
    """
    From raw scan events, extract one intake time per day.
    Uses only 'present' events (bottle picked up) as the intake marker.
    Returns list of dicts: [{date, time_minutes, timestamp}, ...]
    """
    intakes = []
    seen_dates = set()

    for scan in scans:
        if scan["event"] != "present":
            continue

        dt = datetime.fromisoformat(scan["timestamp"])
        date_str = dt.strftime("%Y-%m-%d")

        # Only take the first pickup per day
        if date_str in seen_dates:
            continue
        seen_dates.add(date_str)

        # Convert time to minutes-from-midnight for math
        time_minutes = dt.hour * 60 + dt.minute

        intakes.append({
            "date":         date_str,
            "time_minutes": time_minutes,
            "timestamp":    scan["timestamp"],
            "hour":         dt.hour,
            "minute":       dt.minute,
        })

    # Sort chronologically
    intakes.sort(key=lambda x: x["date"])
    return intakes


def check_hold_duration(scans, min_seconds=5):
    """
    Suspicious pickup check:
    If bottle was held for less than min_seconds, flag as suspicious.
    Returns list of suspicious dates.
    """
    suspicious = []
    present_times = {}

    for scan in scans:
        dt = datetime.fromisoformat(scan["timestamp"])
        date_str = dt.strftime("%Y-%m-%d")

        if scan["event"] == "present":
            present_times[date_str] = dt
        elif scan["event"] == "absent" and date_str in present_times:
            held = (dt - present_times[date_str]).total_seconds()
            if held < min_seconds:
                suspicious.append({
                    "date": date_str,
                    "held_seconds": round(held, 1)
                })

    return suspicious


def zscore_analysis(intakes, window_days=7):
    """
    Layer 1: Z-score rule engine.
    Compares recent intake times against the rolling average.
    Works with as few as 3 days of data.

    Returns drift_per_day and anomaly flags per day.
    """
    if len(intakes) < 3:
        return None, []

    results = []
    times = [r["time_minutes"] for r in intakes]

    for i in range(len(intakes)):
        # Rolling window: last N days before today
        start = max(0, i - window_days)
        window = times[start:i] if i > 0 else []

        if len(window) < 2:
            results.append({**intakes[i], "zscore": 0.0, "is_anomaly": False})
            continue

        mean = statistics.mean(window)
        stdev = statistics.stdev(window) or 1  # avoid divide-by-zero

        zscore = abs((times[i] - mean) / stdev)
        is_anomaly = zscore > 2.0  # standard threshold

        results.append({
            **intakes[i],
            "zscore":     round(zscore, 2),
            "window_mean": round(mean, 1),
            "is_anomaly":  is_anomaly
        })

    # Calculate drift: slope of intake times over last 5 days
    recent = times[-5:] if len(times) >= 5 else times
    if len(recent) >= 2:
        drift_per_day = (recent[-1] - recent[0]) / max(len(recent) - 1, 1)
    else:
        drift_per_day = 0.0

    return round(drift_per_day, 2), results


def isolation_forest_analysis(intakes):
    """
    Layer 2: Isolation Forest ML model.
    Needs scikit-learn installed and at least 7 days of data.
    More robust than Z-score for complex drift patterns.
    """
    if not ML_AVAILABLE or len(intakes) < 7:
        return None

    times = np.array([r["time_minutes"] for r in intakes]).reshape(-1, 1)

    model = IsolationForest(
        contamination=0.15,   # expect ~15% anomalous readings
        random_state=42,
        n_estimators=100
    )
    model.fit(times)

    scores = model.decision_function(times)   # negative = more anomalous
    labels = model.predict(times)              # -1 = anomaly, 1 = normal

    results = []
    for i, intake in enumerate(intakes):
        results.append({
            **intake,
            "if_score":    round(float(scores[i]), 4),
            "if_anomaly":  labels[i] == -1
        })

    return results


def compute_risk_level(drift_per_day, recent_anomaly_count, suspicious_pickups):
    """
    Maps drift + anomaly count → risk level string.

    LOW     : everything normal
    WARNING : drift starting, or 1–2 anomalous days
    HIGH    : significant drift, 3+ anomalous days, or suspicious pickups
    """
    score = 0

    # Drift contribution (minutes per day)
    if abs(drift_per_day) >= 15:
        score += 1
    if abs(drift_per_day) >= 30:
        score += 1

    # Anomaly count contribution
    score += min(recent_anomaly_count, 3)

    # Suspicious pickup penalty
    score += len(suspicious_pickups)

    if score == 0:
        return "LOW", score
    elif score <= 2:
        return "WARNING", score
    else:
        return "HIGH", score


def predict_tomorrow(intakes, drift_per_day):
    """
    Predicts what time the patient will take their medication tomorrow,
    based on current trend.
    """
    if not intakes:
        return "Unknown"

    last_time_minutes = intakes[-1]["time_minutes"]
    predicted_minutes = last_time_minutes + drift_per_day

    # Clamp to reasonable range (4 AM – 11:59 PM)
    predicted_minutes = max(240, min(1439, predicted_minutes))

    hours   = int(predicted_minutes) // 60
    minutes = int(predicted_minutes) % 60
    return f"{hours:02d}:{minutes:02d}"


def run_analysis(scans, config=None):
    """
    Main entry point. Runs full analysis pipeline.
    Returns a result dict ready to be saved to Firebase.
    """
    config = config or {}
    window_days  = config.get("anomaly_window_days", 7)
    min_hold_sec = config.get("min_hold_duration_seconds", 5)

    print("── Running analysis pipeline ──────────────────────────────")

    # Step 1: Extract daily intakes
    intakes = extract_daily_intakes(scans)
    print(f"  Days of data   : {len(intakes)}")

    if not intakes:
        print("  No intake data found.")
        return None

    # Step 2: Hold duration check (suspicious pickups)
    suspicious = check_hold_duration(scans, min_seconds=min_hold_sec)
    if suspicious:
        print(f"  Suspicious pickups: {len(suspicious)} day(s)")
        for s in suspicious:
            print(f"    {s['date']} — held only {s['held_seconds']}s")

    # Step 3: Z-score analysis
    drift_per_day, zscore_results = zscore_analysis(intakes, window_days)
    recent_zanomalies = sum(
        1 for r in zscore_results[-5:] if r.get("is_anomaly")
    )
    print(f"  Drift per day  : {drift_per_day} min")
    print(f"  Z-score anomalies (last 5 days): {recent_zanomalies}")

    # Step 4: Isolation Forest (if available + enough data)
    if_results = isolation_forest_analysis(intakes)
    if if_results:
        recent_if_anomalies = sum(
            1 for r in if_results[-5:] if r.get("if_anomaly")
        )
        print(f"  IF anomalies   (last 5 days): {recent_if_anomalies}")
        # Use the stricter count
        anomaly_count = max(recent_zanomalies, recent_if_anomalies)
    else:
        anomaly_count = recent_zanomalies
        print("  Isolation Forest: skipped (need 7+ days or scikit-learn)")

    # Step 5: Risk level
    risk_level, risk_score = compute_risk_level(
        drift_per_day, anomaly_count, suspicious
    )
    print(f"  Risk level     : {risk_level}  (score={risk_score})")

    # Step 6: Predict tomorrow
    predicted_time = predict_tomorrow(intakes, drift_per_day)
    print(f"  Predicted tomorrow: {predicted_time}")
    print("───────────────────────────────────────────────────────────\n")

    last = intakes[-1]

    return {
        "risk_score":            risk_score,
        "risk_level":            risk_level,
        "drift_minutes_per_day": drift_per_day,
        "recent_anomaly_count":  anomaly_count,
        "suspicious_pickups":    len(suspicious),
        "last_dose_time":        f"{last['hour']:02d}:{last['minute']:02d}",
        "last_dose_date":        last["date"],
        "predicted_tomorrow_time": predicted_time,
        "total_days_tracked":    len(intakes),
        "ml_method":             "IsolationForest+ZScore" if if_results else "ZScore"
    }


# ── Standalone test ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    try:
        scans = load_simulated_data("simulated_scans.json")
        print(f"Loaded {len(scans)} scan events from simulated_scans.json\n")
    except FileNotFoundError:
        print("simulated_scans.json not found.")
        print("Run simulate_data.py first:  python simulate_data.py\n")
        exit(1)

    result = run_analysis(scans)

    print("Final result dict (this gets saved to Firebase):")
    print(json.dumps(result, indent=2))
